"""Initial migration

Revision ID: 3174eba30dd8
Revises: 
Create Date: 2024-11-06 23:02:41.673638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3174eba30dd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_style', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('report_style')

    # ### end Alembic commands ###
